POST http://localhost:8080/api/count
Content-Type: application/json

{
  "message": "a       b"
}


###
#-----------#

POST http://localhost:8080/api/space/split?separator=comma
Content-Type: application/json

{
  "message": "a       b"
}


###
#-----------#

POST http://localhost:8080/api/space/split?separator=colon
Content-Type: application/json

{
  "message": "a       b"
}


###
#-----------#

POST http://localhost:8080/api/space/split?separator=semicolon
Content-Type: application/json

{
  "message": "a       b"
}


###
#-----------#

POST http://localhost:8080/api/space/split?separator=slash
Content-Type: application/json

{
  "message": "a    \n dfa\n dfasdf\n  b"
}


###
#-----------#
GET http://localhost:8080/user
Content-Type: application/json


###
#-----------#

GET http://localhost:8080/string/abc?operation=REVERSE
Content-Type: application/json


###
#-----------#

GET http://localhost:8080/string/abc?operation=UPPER
Content-Type: application/json


###
#-----------#

GET http://localhost:8080/string/ABC?operation=LOWER
Content-Type: application/json


###
#-----------#

POST http://localhost:8080/user
Content-Type: application/json

{
  "username": "asasdas",
  "screenName": "aasassas",
  "email": "another.email@email.com"
}

###
#-----------#

POST https://hello-kotlin-project.herokuapp.com/api/space/split?separator=slash
Content-Type: application/json

{
  "message": "a    \n dfa\n dfasdf\n  b"
}


###
#-----------#

POST http://localhost:8080/order/dsi
Content-Type: application/json

{
  "data": [
    {
      "technic_model": "SINOMACH 955T",
      "gos_numb": "01 FA 733",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "LCL955T0VK1000895",
      "send_id": 168854,
      "reg_date": "04.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "04.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "1219H006256",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000001"
    },
    {
      "technic_model": "SHANTUI SD16",
      "gos_numb": "01 FA 738",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "",
      "send_id": 168855,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000006"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 734",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004698",
      "send_id": 168856,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363213",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000003"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 735",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ616LK0001640",
      "send_id": 168857,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366342",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000004"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 736",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKH616HK0001641",
      "send_id": 168858,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366334",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000005"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 772",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905TK0004733",
      "send_id": 168859,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22369150",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000048"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 773",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004734",
      "send_id": 168860,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363371",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000049"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 774",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905KK0004735",
      "send_id": 168861,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363363",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000050"
    }
  ],
  "getVehiclesByCustomerId": "select * from tbl_vehicles where owner_id = 213",
  "getCustomerDataById": "select * from customers where id = 213",
  "isLegalEntity": "select type from customers where id = 213",
  "message": "Success",
  "status": "success"
}


###
#-----------#


POST http://localhost:8080/order/dsi/qrcode
Content-Type: application/json

{
  "data": [
    {
      "technic_model": "SINOMACH 955T",
      "gos_numb": "01 FA 733",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "LCL955T0VK1000895",
      "send_id": 168854,
      "reg_date": "04.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "04.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "1219H006256",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000001"
    },
    {
      "technic_model": "SHANTUI SD16",
      "gos_numb": "01 FA 738",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "",
      "send_id": 168855,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000006"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 734",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004698",
      "send_id": 168856,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363213",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000003"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 735",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ616LK0001640",
      "send_id": 168857,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366342",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000004"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 736",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKH616HK0001641",
      "send_id": 168858,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366334",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000005"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 772",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905TK0004733",
      "send_id": 168859,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22369150",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000048"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 773",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004734",
      "send_id": 168860,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363371",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000049"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 774",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905KK0004735",
      "send_id": 168861,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363363",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000050"
    }
  ],
  "getVehiclesByCustomerId": "select * from tbl_vehicles where owner_id = 213",
  "getCustomerDataById": "select * from customers where id = 213",
  "isLegalEntity": "select type from customers where id = 213",
  "message": "Success",
  "status": "success"
}


###
#-----------#


POST http://localhost:8080/order/dsi/withqrcode
Content-Type: application/json

{
  "data": [
    {
      "technic_model": "SINOMACH 955T",
      "gos_numb": "01 FA 733",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "LCL955T0VK1000895",
      "send_id": 168854,
      "reg_date": "04.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "04.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "1219H006256",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000001"
    },
    {
      "technic_model": "SHANTUI SD16",
      "gos_numb": "01 FA 738",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "",
      "send_id": 168855,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000006"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 734",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004698",
      "send_id": 168856,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363213",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000003"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 735",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ616LK0001640",
      "send_id": 168857,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366342",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000004"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 736",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKH616HK0001641",
      "send_id": 168858,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366334",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000005"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 772",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905TK0004733",
      "send_id": 168859,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22369150",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000048"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 773",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004734",
      "send_id": 168860,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363371",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000049"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 774",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905KK0004735",
      "send_id": 168861,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363363",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000050"
    }
  ],
  "getVehiclesByCustomerId": "select * from tbl_vehicles where owner_id = 213",
  "getCustomerDataById": "select * from customers where id = 213",
  "isLegalEntity": "select type from customers where id = 213",
  "message": "Success",
  "status": "success",
  "date": "2021-йил 31-декабр",
  "number": 100

}


###

#-----------#
POST http://localhost:8080/order/dsi/withqrcode/base64
Content-Type: application/json

{
  "data": [
    {
      "technic_model": "SINOMACH 955T",
      "gos_numb": "01 FA 733",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "LCL955T0VK1000895",
      "send_id": 168854,
      "reg_date": "04.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "04.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "1219H006256",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000001"
    },
    {
      "technic_model": "SHANTUI SD16",
      "gos_numb": "01 FA 738",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "",
      "send_id": 168855,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000006"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 734",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004698",
      "send_id": 168856,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363213",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000003"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 735",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ616LK0001640",
      "send_id": 168857,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366342",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000004"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 736",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKH616HK0001641",
      "send_id": 168858,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366334",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000005"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 772",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905TK0004733",
      "send_id": 168859,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22369150",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000048"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 773",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004734",
      "send_id": 168860,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363371",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000049"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 774",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905KK0004735",
      "send_id": 168861,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363363",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000050"
    }
  ],
  "getVehiclesByCustomerId": "select * from tbl_vehicles where owner_id = 213",
  "getCustomerDataById": "select * from customers where id = 213",
  "isLegalEntity": "select type from customers where id = 213",
  "message": "Success",
  "status": "success",
  "date": "2021-йил 31-декабр",
  "number": 100

}


###
#-----------#

#-----------# test
POST http://localhost:8080/order/dsi/withqrcode/base64
Content-Type: application/json

{
  "data": [
    {
      "technic_model": "SINOMACH 955T",
      "gos_numb": "01 FA 733",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "LCL955T0VK1000895",
      "send_id": 171726,
      "reg_date": "04.12.2019",
      "send_date": "30.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "04.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "1219H006256",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000001"
    },
    {
      "technic_model": "SHANTUI SD16",
      "gos_numb": "01 FA 738",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "",
      "send_id": 171727,
      "reg_date": "05.12.2019",
      "send_date": "30.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000006"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 734",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004698",
      "send_id": 171728,
      "reg_date": "05.12.2019",
      "send_date": "30.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363213",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000003"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 735",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ616LK0001640",
      "send_id": 171729,
      "reg_date": "05.12.2019",
      "send_date": "30.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366342",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000004"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 736",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKH616HK0001641",
      "send_id": 171730,
      "reg_date": "05.12.2019",
      "send_date": "30.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366334",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000005"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 772",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905TK0004733",
      "send_id": 171731,
      "reg_date": "13.12.2019",
      "send_date": "30.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22369150",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000048"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 773",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004734",
      "send_id": 171732,
      "reg_date": "13.12.2019",
      "send_date": "30.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363371",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000049"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 774",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905KK0004735",
      "send_id": 171733,
      "reg_date": "13.12.2019",
      "send_date": "30.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363363",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000050"
    }
  ],
  "getVehiclesByCustomerId": "select * from tbl_vehicles where owner_id = 213",
  "getCustomerDataById": "select * from customers where id = 213",
  "isLegalEntity": "select type from customers where id = 213",
  "message": "Success",
  "status": "success",
  "date": "2021-йил 31-декабр",
  "number": 100

}


###
#-----------#

POST https://hello-kotlin-project.herokuapp.com/order/dsi/withqrcode/base64
Content-Type: application/json

{
  "data": [
    {
      "technic_model": "SINOMACH 955T",
      "gos_numb": "01 FA 733",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "LCL955T0VK1000895",
      "send_id": 168854,
      "reg_date": "04.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "04.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "1219H006256",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000001"
    },
    {
      "technic_model": "SHANTUI SD16",
      "gos_numb": "01 FA 738",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "",
      "send_id": 168855,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000006"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 734",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004698",
      "send_id": 168856,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363213",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000003"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 735",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ616LK0001640",
      "send_id": 168857,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366342",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000004"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 736",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKH616HK0001641",
      "send_id": 168858,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366334",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000005"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 772",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905TK0004733",
      "send_id": 168859,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22369150",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000048"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 773",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004734",
      "send_id": 168860,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363371",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000049"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 774",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905KK0004735",
      "send_id": 168861,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363363",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000050"
    }
  ],
  "getVehiclesByCustomerId": "select * from tbl_vehicles where owner_id = 213",
  "getCustomerDataById": "select * from customers where id = 213",
  "isLegalEntity": "select type from customers where id = 213",
  "message": "Success",
  "status": "success",
  "date": "2021-йил 31-декабр",
  "number": 100

}


###
#-----------#



#POST http://195.158.30.178/application
#POST https://hello-kotlin-project.herokuapp.com/order/dsi/withqrcode/base64/v2
POST localhost:8080/order/dsi/withqrcode/base64/v2
Content-Type: application/json

{
  "data": [
    {
      "technic_model": "SINOMACH 955T",
      "gos_numb": "01 FA 733",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "LCL955T0VK1000895",
      "send_id": 168854,
      "reg_date": "04.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "04.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "1219H006256",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000001"
    },
    {
      "technic_model": "SHANTUI SD16",
      "gos_numb": "01 FA 738",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "",
      "send_id": 168855,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000006"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 734",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004698",
      "send_id": 168856,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363213",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000003"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 735",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ616LK0001640",
      "send_id": 168857,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366342",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000004"
    },
    {
      "technic_model": "Robex-210W-9S",
      "gos_numb": "01 FA 736",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKH616HK0001641",
      "send_id": 168858,
      "reg_date": "05.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "05.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22366334",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000005"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 772",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905TK0004733",
      "send_id": 168859,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22369150",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000048"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 773",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905PK0004734",
      "send_id": 168860,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363371",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000049"
    },
    {
      "technic_model": "Robex-330LC-9S",
      "gos_numb": "01 FA 774",
      "adress": "17 mavze  34 uy 12 xonadon",
      "certificate_ser": "UZ-AA",
      "chasis_numb": "HHKHZ905KK0004735",
      "send_id": 168861,
      "reg_date": "13.12.2019",
      "send_date": "28.12.2021",
      "made_year": 2019,
      "district": "Chilonzor",
      "technic_owner_address": "17 mavze  34 uy 12 xonadon",
      "tin": 304546511,
      "name": "SUCCESS TRADE LIZING",
      "certificate_given_date": "13.12.2019",
      "technic_type": "vehicle",
      "engine_numb": "22363363",
      "region": "Toshkent shahri",
      "technic_color": "Sariq",
      "certificate_numb": "000050"
    }
  ],
  "getVehiclesByCustomerId": "select * from tbl_vehicles where owner_id = 213",
  "getCustomerDataById": "select * from customers where id = 213",
  "isLegalEntity": "select type from customers where id = 213",
  "message": "Success",
  "status": "success",
  "date": "2021-йил 31-декабр",
  "number": 100

}


###
#-----------#



